/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.common.model.visibility.validation;

import org.lunifera.ecview.core.common.model.visibility.YColorType;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.common.model.visibility.YColor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YColorValidator {
	boolean validate();

	boolean validateRed(int value);
	boolean validateGreen(int value);
	boolean validateBlue(int value);
	boolean validateThemeId(String value);
	boolean validateType(YColorType value);
}
