/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.common.model.visibility.validation;

import org.eclipse.emf.common.util.EList;
import org.lunifera.ecview.core.common.model.binding.YBindingEndpoint;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.common.model.visibility.YVisibilityProcessor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YVisibilityProcessorValidator {
	boolean validate();

	boolean validateDataUsed(EList<YBindingEndpoint> value);
	boolean validateTriggersOn(EList<YBindingEndpoint> value);
	boolean validateDelegate(Class<?> value);
	boolean validateDelegateQualifiedName(String value);
}
