<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extension" nsURI="http://eclipse.org/emf/ecp/ecview/extension"
    nsPrefix="basicextension">
  <eClassifiers xsi:type="ecore:EClass" name="YTextField" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YTextDatatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGridLayout" eSuperTypes="core.ecore#//YLayout core.ecore#//YSpacingable core.ecore#//YMarginable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellStyles" upperBound="-1"
        eType="#//YGridLayoutCellStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of columns the GridLayout should contain.&#x9;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillHorizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If false, then the width of all elements contained in the grid layout will be decreased to their preferred width or their miminum width. If no alignment is defined for a child, this setting will become its default.&#xA;Eg if child has not a alignment, the horizontal alignment will become FILL if fillHorizontal is true. Otherwise the ui-kit default will be used as the horizontal alignment."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If false, then the width of all elements contained in the grid layout will be decreased to their preferred height or their miminum height. If no alignment is defined for a child, this setting will become its default.&#xA;Eg if child has not a alignment, the vertical alignment will become FILL if fillVertical is true. Otherwise the ui-kit default will be used as the vertical alignment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGridLayoutCellStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass core.ecore#//YEmbeddable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//YAlignment"
        defaultValueLiteral="UNDEFINED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The alignment of the ui element relative to its grid cell."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spanInfo" eType="#//YSpanInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YHorizontalLayout" eSuperTypes="core.ecore#//YLayout core.ecore#//YSpacingable core.ecore#//YMarginable">
    <eOperations name="getCellStyle" eType="#//YHorizontalLayoutCellStyle">
      <eParameters name="element" eType="ecore:EClass core.ecore#//YEmbeddable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellStyles" upperBound="-1"
        eType="#//YHorizontalLayoutCellStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillHorizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If false, then the width of all elements contained in the grid layout will be decreased to their preferred width or their miminum width. If no alignment is defined for a child, this setting will become its default.&#xA;Eg if child has not a alignment, the horizontal alignment will become FILL if fillHorizontal is true. Otherwise the ui-kit default will be used as the horizontal alignment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YHorizontalLayoutCellStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass core.ecore#//YEmbeddable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//YAlignment"
        defaultValueLiteral="UNDEFINED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The alignment of the ui element relative to its grid cell."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVerticalLayout" eSuperTypes="core.ecore#//YLayout core.ecore#//YSpacingable core.ecore#//YMarginable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellStyles" upperBound="-1"
        eType="#//YVerticalLayoutCellStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If false, then the width of all elements contained in the grid layout will be decreased to their preferred height or their miminum height. If no alignment is defined for a child, this setting will become its default.&#xA;Eg if child has not a alignment, the vertical alignment will become FILL if fillVertical is true. Otherwise the ui-kit default will be used as the vertical alignment."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVerticalLayoutCellStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass core.ecore#//YEmbeddable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//YAlignment"
        defaultValueLiteral="UNDEFINED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The alignment of the ui element relative to its grid cell."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YAlignment">
    <eLiterals name="BOTTOM_LEFT"/>
    <eLiterals name="BOTTOM_CENTER" value="1" literal="BOTTOM_CENTER"/>
    <eLiterals name="BOTTOM_RIGHT" value="2" literal="BOTTOM_RIGHT"/>
    <eLiterals name="BOTTOM_FILL" value="3" literal="BOTTOM_FILL"/>
    <eLiterals name="MIDDLE_LEFT" value="4" literal="MIDDLE_LEFT"/>
    <eLiterals name="MIDDLE_CENTER" value="5" literal="MIDDLE_CENTER"/>
    <eLiterals name="MIDDLE_RIGHT" value="6" literal="MIDDLE_RIGHT"/>
    <eLiterals name="MIDDLE_FILL" value="7" literal="MIDDLE_FILL"/>
    <eLiterals name="TOP_LEFT" value="8"/>
    <eLiterals name="TOP_CENTER" value="9" literal="TOP_CENTER"/>
    <eLiterals name="TOP_RIGHT" value="10" literal="TOP_RIGHT"/>
    <eLiterals name="TOP_FILL" value="11" literal="TOP_FILL"/>
    <eLiterals name="FILL_FILL" value="12" literal="FILL_FILL"/>
    <eLiterals name="FILL_LEFT" value="13" literal="FILL_LEFT"/>
    <eLiterals name="FILL_CENTER" value="14" literal="FILL_CENTER"/>
    <eLiterals name="FILL_RIGHT" value="15" literal="FILL_RIGHT"/>
    <eLiterals name="UNDEFINED" value="16" literal="UNDEFINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YSpanInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The column index of the cell that should contain the Upper-Left-Edge of the element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The row index of the cell that should contain the Upper-Left-Edge of the element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The column index of the cell that should contain the Lower-Right-Edge of the element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The row index of the cell that should contain the Lower-Right-Edge of the element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTable" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YTableDatatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YLabel" eSuperTypes="core.ecore#//YField core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTextArea" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YTextAreaDatatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCheckBox" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YCheckBoxDatatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YInput" abstract="true" eSuperTypes="core.ecore#//YField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDecimalField" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YDecimalDatatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YNumericField" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YNumericDatatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YComboBox" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YComboBoxDatatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YList" eSuperTypes="#//YInput core.ecore#//YBindable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datadescription" eType="ecore:EClass datatypes.ecore#//YDatadescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="ecore:EClass datatypes.ecore#//YListDataType"/>
  </eClassifiers>
</ecore:EPackage>
