/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.common.model.core.validation;


/**
 * A sample validator interface for {@link org.lunifera.ecview.core.common.model.core.YExposedAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YExposedActionValidator {
	boolean validate();

	boolean validateIcon(String value);

	boolean validateLabel(String value);

	boolean validateLabelI18nKey(String value);

	boolean validateExternalClickTime(long value);

	boolean validateInternalClickTime(long value);

	boolean validateExecutedNotificationTime(long value);

	boolean validateCanceledNotificationTime(long value);

	boolean validateLastClickTime(long value);

	boolean validateExecutedTime(long value);

	boolean validateCanceledTime(long value);

	boolean validateCheckDirty(boolean value);
}
