/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.common.model.core.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.ecview.core.common.model.core.YBeanSlot;
import org.lunifera.ecview.core.common.model.core.YCommandSet;
import org.lunifera.ecview.core.common.model.core.YView;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.common.model.core.YViewSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YViewSetValidator {
	boolean validate();

	boolean validateViews(EList<YView> value);
	boolean validateBeanSlots(EList<YBeanSlot> value);

	boolean validateCommandSet(EList<YCommandSet> value);
}
