<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visibility" nsURI="http://eclipse.org/emf/ecp/ecview/common/visibility"
    nsPrefix="visibility">
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityProcessor" abstract="true"
      eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onMatch" lowerBound="1"
        eType="#//YVisibilityProperties" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="ecore:EClass core.ecore#//YVisibilityProcessable" eOpposite="core.ecore#//YVisibilityProcessable/visibilityProcessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YRuledVisibilityProcessor" eSuperTypes="#//YVisibilityProcessor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//YVisibilityRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityRule" abstract="true" eSuperTypes="core.ecore#//YElement">
    <eOperations name="createRuleEndpoint" eType="#//YVisibilityRuleBindingEndpoint">
      <eParameters name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEndpoints" upperBound="-1"
        eType="#//YVisibilityRuleBindingEndpoint" eOpposite="#//YVisibilityRuleBindingEndpoint/rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchMeansFalse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityProperties" eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strikethrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//YColor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foregroundColor" eType="#//YColor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YColor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="themeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//YColorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YColorType">
    <eLiterals name="THEME" literal="THEME"/>
    <eLiterals name="RGB" value="1" literal="RGB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityRuleBindingEndpoint" eSuperTypes="binding.ecore#//YValueBindingEndpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//YVisibilityRule"
        eOpposite="#//YVisibilityRule/bindingEndpoints"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YBooleanValueRule" abstract="true" eSuperTypes="#//YVisibilityRule">
    <eOperations name="createRuleEndpoint" eType="#//YVisibilityRuleBindingEndpoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YRegexpRule" abstract="true" eSuperTypes="#//YVisibilityRule">
    <eOperations name="createRuleEndpoint" eType="#//YVisibilityRuleBindingEndpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDecimalValueRule" abstract="true" eSuperTypes="#//YVisibilityRule">
    <eOperations name="createRuleEndpoint" eType="#//YVisibilityRuleBindingEndpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="option" eType="#//YDecimalValueRuleOption"
        defaultValueLiteral="EQUAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YDecimalValueRuleOption">
    <eLiterals name="EQUAL" literal="EQUAL"/>
    <eLiterals name="LOWER" value="1" literal="LOWER"/>
    <eLiterals name="LOWER_EQUAL" value="2" literal="LOWER_EQUAL"/>
    <eLiterals name="GREATER" value="3" literal="GREATER"/>
    <eLiterals name="GREATER_EQUAL" value="4" literal="GREATER_EQUAL"/>
    <eLiterals name="NOT_EQUAL" value="5" literal="NOT_EQUAL"/>
  </eClassifiers>
</ecore:EPackage>
