<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visibility" nsURI="http://eclipse.org/emf/ecp/ecview/common/visibility"
    nsPrefix="visibility">
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityProcessor" eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityRule" eSuperTypes="core.ecore#//YElement"/>
</ecore:EPackage>
