<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes" nsURI="http://eclipse.org/emf/ecp/ecview/extension/datatypes"
    nsPrefix="datatypes">
  <eClassifiers xsi:type="ecore:EClass" name="YTextDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxlength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minlength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regexpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTextAreaDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YNumericDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grouping" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markNegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDecimalDatatype" eSuperTypes="#//YNumericDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTableDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YCheckBoxDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YComboBoxDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YListDataType" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YBrowserDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YDateTimeDatatype" eSuperTypes="../../org.eclipse.emf.ecp.ecview.common.model/model/datatypes.ecore#//YDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//YDateTimeFormat"
        defaultValueLiteral="DATE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YDateTimeFormat">
    <eLiterals name="DATE"/>
    <eLiterals name="TIME" value="1" literal="TIME"/>
    <eLiterals name="DATE_TIME" value="2" literal="DATE_TIME"/>
  </eClassifiers>
</ecore:EPackage>
