/**
 *
 * $Id$
 */
package org.eclipse.emf.ecp.ecview.common.model.visibility.validation;

import org.eclipse.emf.ecp.ecview.common.model.visibility.YVisibilityRule;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecp.ecview.common.model.visibility.YVisibilityRuleBindingEndpoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YVisibilityRuleBindingEndpointValidator {
	boolean validate();

	boolean validateRule(YVisibilityRule value);
	boolean validateAttribute(String value);
}
