/**
 *
 * $Id$
 */
package org.eclipse.emf.ecp.ecview.common.model.binding.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecp.ecview.common.model.binding.YBinding;

/**
 * A sample validator interface for {@link org.eclipse.emf.ecp.ecview.common.model.binding.YBindingSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YBindingSetValidator {
	boolean validate();

	boolean validateBindings(EList<YBinding> value);
}
