/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.extension.model.extension.validation;

import org.lunifera.ecview.core.extension.model.extension.YTable;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.extension.model.extension.YAddToTableCommand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YAddToTableCommandValidator {
	boolean validate();

	boolean validateTable(YTable value);

	boolean validateTrigger(Object value);
}
