/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.extension.model.extension.validation;

import java.io.InputStream;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.extension.model.extension.YBrowserStreamInput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YBrowserStreamInputValidator {
	boolean validate();

	boolean validateFilename(String value);
	boolean validateInputStream(InputStream value);

	boolean validateMimeType(String value);
}
