/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.extension.model.extension.validation;

import org.lunifera.ecview.core.common.model.datatypes.YDatadescription;

import org.lunifera.ecview.core.extension.model.datatypes.YTextDatatype;

/**
 * A sample validator interface for {@link org.lunifera.ecview.core.extension.model.extension.YTextField}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YTextFieldValidator {
	boolean validate();

	boolean validateDatatype(YTextDatatype value);
	boolean validateDatadescription(YDatadescription value);
	boolean validateValue(String value);
}
