<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes" nsURI="http://lunifera.org/ecview/v1/extension/datatypes"
    nsPrefix="datatypes">
  <eClassifiers xsi:type="ecore:EClass" name="YTextDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YMaxLengthValidationConfig ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YMinLengthValidationConfig ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YRegexpValidationConfig"/>
  <eClassifiers xsi:type="ecore:EClass" name="YTextAreaDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YMinLengthValidationConfig ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YMaxLengthValidationConfig ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YRegexpValidationConfig"/>
  <eClassifiers xsi:type="ecore:EClass" name="YNumericDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YRegexpValidationConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grouping" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markNegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDecimalDatatype" eSuperTypes="#//YNumericDatatype ../../org.lunifera.ecview.core.common.model/model/validation.ecore#//YRegexpValidationConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTableDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YCheckBoxDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YComboBoxDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YListDataType" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YOptionsGroupDataType" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YBrowserDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YDateTimeDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//YDateTimeFormat"
        defaultValueLiteral="DATE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="#//YDateTimeResolution"
        defaultValueLiteral="UNDEFINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YDateTimeFormat">
    <eLiterals name="DATE"/>
    <eLiterals name="TIME" value="1" literal="TIME"/>
    <eLiterals name="DATE_TIME" value="2" literal="DATE_TIME"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YDateTimeResolution">
    <eLiterals name="SECOND" literal="SECOND"/>
    <eLiterals name="MINUTE" value="1" literal="MINUTE"/>
    <eLiterals name="HOUR" value="2" literal="HOUR"/>
    <eLiterals name="DAY" value="3" literal="DAY"/>
    <eLiterals name="MONTH" value="4" literal="MONTH"/>
    <eLiterals name="YEAR" value="5" literal="YEAR"/>
    <eLiterals name="UNDEFINED" value="6" literal="UNDEFINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTreeDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YProgressBarDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YTabSheetDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="YMasterDetailDatatype" eSuperTypes="../../org.lunifera.ecview.core.common.model/model/datatypes.ecore#//YDatatype"/>
</ecore:EPackage>
