/**
 *
 * $Id$
 */
package org.lunifera.ecview.core.common.model.core.validation;

import org.lunifera.ecview.core.common.model.core.YEmbeddable;
import org.lunifera.ecview.core.common.model.datatypes.YDatadescription;


/**
 * A sample validator interface for {@link org.lunifera.ecview.core.common.model.core.YDialog}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YDialogValidator {
	boolean validate();

	boolean validateContent(YEmbeddable value);

	boolean validateModal(boolean value);

	boolean validateResizeable(boolean value);

	boolean validateDraggable(boolean value);

	boolean validateClosable(boolean value);

	boolean validateValue(Object value);

	boolean validateType(Class<?> value);

	boolean validateEmfNsURI(String value);

	boolean validateTypeQualifiedName(String value);

	boolean validateDatadescription(YDatadescription value);

}
