<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes" nsURI="http://lunifera.org/ecview/v1/core/datatypes"
    nsPrefix="datatypes">
  <eClassifiers xsi:type="ecore:EClass" name="YDtBase" abstract="true" interface="true"
      eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDatatype" abstract="true" interface="true"
      eSuperTypes="#//YDtBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validators" upperBound="-1"
        eType="ecore:EClass validation.ecore#//YValidator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDatadescription" eSuperTypes="#//YDtBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelI18nKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
