<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visibility" nsURI="http://lunifera.org/ecview/v1/core/visibility"
    nsPrefix="visibility">
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityProcessor" eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataUsed" upperBound="-1"
        eType="ecore:EClass binding.ecore#//YBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggersOn" upperBound="-1"
        eType="ecore:EClass binding.ecore#//YBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegate">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegateQualifiedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVisibilityProperties" eSuperTypes="core.ecore#//YElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="border" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strikethrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" eType="#//YColor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foregroundColor" eType="#//YColor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColorCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foregroundColorCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YColor">
    <eLiterals name="UNDEFINED" literal="UNDEFINED"/>
    <eLiterals name="GREEN" value="1" literal="green"/>
    <eLiterals name="BLUE" value="2" literal="blue"/>
    <eLiterals name="YELLOW" value="3" literal="yellow"/>
    <eLiterals name="RED" value="4" literal="red"/>
    <eLiterals name="BLACK" value="5" literal="black"/>
    <eLiterals name="WHITE" value="6" literal="white"/>
    <eLiterals name="GRAY" value="7" literal="gray"/>
    <eLiterals name="LIGHT_GRAY" value="8" literal="light-gray"/>
    <eLiterals name="DARK_GRAY" value="9" literal="dark-gray"/>
  </eClassifiers>
</ecore:EPackage>
