<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extension" nsURI="http://eclipse.org/emf/emfclient/uimodel/basicExtension"
    nsPrefix="basicextension">
  <eClassifiers xsi:type="ecore:EClass" name="YUiTextField" eSuperTypes="uimodel.ecore#//YUiField"/>
  <eClassifiers xsi:type="ecore:EClass" name="YUiGridLayout" eSuperTypes="uimodel.ecore#//YUiLayout uimodel.ecore#//YUiSpacingable uimodel.ecore#//YUiMarginable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellStyles" upperBound="-1"
        eType="#//YUiGridLayoutCellStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiGridLayoutCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="YUiGridLayoutCellStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass uimodel.ecore#//YUiEmbeddable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//YUiAlignment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grabHorizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grabVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spanInfo" eType="#//YUiSpanInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YUiAlignment">
    <eLiterals name="BOTTOM_LEFT"/>
    <eLiterals name="BOTTOM_CENTER" value="1" literal="BOTTOM_CENTER"/>
    <eLiterals name="BOTTOM_RIGHT" value="2" literal="BOTTOM_RIGHT"/>
    <eLiterals name="BOTTOM_FILL" value="3" literal="BOTTOM_FILL"/>
    <eLiterals name="MIDDLE_LEFT" value="4" literal="MIDDLE_LEFT"/>
    <eLiterals name="MIDDLE_CENTER" value="5" literal="MIDDLE_CENTER"/>
    <eLiterals name="MIDDLE_RIGHT" value="6" literal="MIDDLE_RIGHT"/>
    <eLiterals name="MIDDLE_FILL" value="7" literal="MIDDLE_FILL"/>
    <eLiterals name="TOP_LEFT" value="8"/>
    <eLiterals name="TOP_CENTER" value="9" literal="TOP_CENTER"/>
    <eLiterals name="TOP_RIGHT" value="10" literal="TOP_RIGHT"/>
    <eLiterals name="TOP_FILL" value="11" literal="TOP_FILL"/>
    <eLiterals name="FILL_FILL" value="12" literal="FILL_FILL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiSpanInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
