<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimodel" nsURI="http://eclipse.org/emf/emfclient/uimodel" nsPrefix="uimodel">
  <eClassifiers xsi:type="ecore:EClass" name="YUiElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiLayout" eSuperTypes="#//YUiEmbeddable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//YUiEmbeddable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiField" eSuperTypes="#//YUiEmbeddable"/>
  <eClassifiers xsi:type="ecore:EClass" name="YUiView" eSuperTypes="#//YUiElement #//YUiCssAble #//YUiMarginable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//YUiViewSet"
        eOpposite="#//YUiViewSet/views"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//YUiEmbeddable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiViewSet" eSuperTypes="#//YUiElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//YUiView" containment="true" eOpposite="#//YUiView/root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiEmbeddable" abstract="true" eSuperTypes="#//YUiElement #//YUiCssAble">
    <eOperations name="getParent" eType="#//YUiLayout"/>
    <eOperations name="getView" eType="#//YUiView"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiCssAble" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiMarginable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="margin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUiSpacingable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spacing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
